parameters:
  opensoft.doctrine_additions_bundle.mapping.eventsubscriber.generatorsubscriber.class: Opensoft\DoctrineAdditionsBundle\Mapping\EventSubscriber\GeneratorSubscriber
  opensoft.doctrine_additions_bundle.mapping.eventsubscriber.mapping_subscriber.class: Opensoft\DoctrineAdditionsBundle\Mapping\EventSubscriber\MappingSubscriber

services:
  opensoft.doctrine_additions_bundle.mapping.eventsubscriber.generatorsubscriber:
    class: %opensoft.doctrine_additions_bundle.mapping.eventsubscriber.generatorsubscriber.class%
    tags:
      -  { name: doctrine.event_subscriber, connection: default }
    arguments:
      - @annotations.reader

  opensoft.doctrine_additions_bundle.mapping.eventsubscriber.mapping_subscriber:
    class: %opensoft.doctrine_additions_bundle.mapping.eventsubscriber.mapping_subscriber.class%
    tags:
      -  { name: doctrine.event_subscriber, connection: default }
    arguments:
      - @annotations.reader
